repos:
  - repo: local
    hooks:
      - id: gofumpt
        name: Run gofumpt
        language: golang
        additional_dependencies: [mvdan.cc/gofumpt@v0.6.0]
        types: [go]
        entry: gofumpt -w
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.57.2
    hooks:
      - id: golangci-lint

