# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Test building with different go versions
run-name: Test building with different go versions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.21"
          - "1.20"
          - "1.19"
          - "1.18"
          - "1.17"
    name: Test building with go-${{ matrix.go }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - run: go build ./cmd/hydroxide
